### ISSUE TITLE
Deleting folders in the users home directory is dangerous

### ISSUE THREAD

**Issue by KristofferC** [KwatMDPhD/PkgRepository.jl#3]
https://github.com/KwatMDPhD/PkgRepository.jl/blob/382bd86eb126ce092e94cd99cedc05ae9a07b9a7/TEMPLATE.jl/test/runtests.jl#L1-L7

will unconditionally delete an existing folder in a user's Downloads directory if it exists. It should probably create a temporary folder instead.

**Comment by KwatMDPhD** [comment]
This `TEMPLATE.test` was created at the top serving as the temporary folder. What do you think about creating temporaries in the download folder? If not, where else would you suggest?
