### ISSUE TITLE
pkgr check

### ISSUE THREAD

**Issue by KatharineME** [KwatMDPhD/PkgRepository.jl#7]
![Screen Shot 2022-02-01 at 13 51 13](https://user-images.githubusercontent.com/20215501/152049324-25ab718a-7aaf-40e3-bbb7-b1ef3548d264.png)

is that a pkgr error or a problem with the Fastq.jl package that I was checking?

**Comment by KwatMDPhD** [comment]
Assertion error. Let's look at this.

**Comment by KwatMDPhD** [comment]
This happens because "---" occurs in Fastq.jl not at all or more than `TEMPLATE.jl/src/TEMPLATE.jl`.
